import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { ensureDatabase, db } from '@/lib/db';
import { verifySession } from '@/lib/auth';
export const runtime = 'nodejs';
async function session(){const c=await cookies();return verifySession(c.get('ps_session')?.value||'');}
export async function GET(req:Request){try{await ensureDatabase();const sql=db();const admin=new URL(req.url).searchParams.get('admin')==='1';if(admin&&!(await session()))return NextResponse.json({error:'Unauthorized'},{status:401});const rows=admin?await sql`SELECT id,title,description,category,image_url,status,published_at,created_at,updated_at FROM site_content ORDER BY created_at DESC`:await sql`SELECT id,title,description,category,image_url,status,published_at,created_at FROM site_content WHERE status='published' ORDER BY COALESCE(published_at,created_at) DESC`;return NextResponse.json({items:rows},{headers:{'Cache-Control':'no-store'}})}catch(error){console.error('CONTENT_GET_ERROR',error);return NextResponse.json({error:'Database belum terhubung. Pastikan DATABASE_URL tersedia di Vercel.'},{status:503})}}
export async function POST(req:Request){try{const s=await session();if(!s)return NextResponse.json({error:'Unauthorized'},{status:401});await ensureDatabase();const body=await req.json();const title=String(body?.title||'').trim().slice(0,180);const description=String(body?.description||'').trim().slice(0,5000);const category=String(body?.category||'Berita').trim().slice(0,80);const imageUrl=String(body?.imageUrl||'').trim().slice(0,1000);const status=body?.status==='draft'?'draft':'published';if(!title||!description)return NextResponse.json({error:'Judul dan deskripsi wajib diisi.'},{status:400});if(imageUrl&&!/^https:\/\//i.test(imageUrl))return NextResponse.json({error:'URL gambar harus menggunakan HTTPS.'},{status:400});const id=`content-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const sql=db();await sql`INSERT INTO site_content (id,title,description,category,image_url,status,published_at) VALUES (${id},${title},${description},${category},${imageUrl},${status},${status==='published'?new Date():null})`;return NextResponse.json({ok:true,id})}catch(error){console.error('CONTENT_POST_ERROR',error);return NextResponse.json({error:'Gagal menyimpan konten.'},{status:500})}}
export async function DELETE(req:Request){try{const s=await session();if(!s||s.role==='staf_informasi')return NextResponse.json({error:'Akses ditolak'},{status:403});await ensureDatabase();const id=String((await req.json())?.id||'').trim();if(!id)return NextResponse.json({error:'ID konten tidak valid.'},{status:400});const sql=db();await sql`DELETE FROM site_content WHERE id=${id}`;return NextResponse.json({ok:true})}catch(error){console.error('CONTENT_DELETE_ERROR',error);return NextResponse.json({error:'Gagal menghapus konten.'},{status:500})}}
