import Link from 'next/link';
import { Activity, ArrowRight, CalendarDays, HeartPulse, Menu, ShieldCheck, Stethoscope, Users, Megaphone, MapPin, Clock3 } from 'lucide-react';
import { LogoLockup, Logo } from '@/components/Logo';

const programs = [['GERMAS', 'Gerakan Masyarakat Hidup Sehat', 'Aktivitas fisik, deteksi dini, dan perilaku hidup bersih sehat.', 'HeartPulse'], ['CKG', 'Cek Kesehatan Gratis', 'Informasi alur, jadwal kegiatan, dan edukasi pemeriksaan kesehatan.', 'Activity'], ['TB & KIA', 'Kesehatan keluarga & pencegahan penyakit', 'Materi edukasi untuk masyarakat Somagede dan wilayah kerja.', 'Users']];
const iconMap = { HeartPulse, Activity, Users };
export default function Home() {
    return <>
        <div className="topbar"><div className="container"><span>Portal Informasi Publik</span><span>Senin–Sabtu · 08.00 WIB s.d. selesai</span></div></div>
        <header className="nav"><div className="container navinner"><LogoLockup /><button className="menu" aria-label="Buka menu"><Menu /></button><nav className="links"><a href="#layanan">Layanan</a><a href="#program">Program</a><a href="#informasi">Informasi</a><a href="#kontak">Kontak</a><Link className="pill" href="/login">Admin</Link></nav></div></header>
        <main>
            <section className="hero"><div className="container heroGrid"><div><div className="eyebrow"><ShieldCheck size={15} /> Layanan kesehatan primer berbasis masyarakat</div><h1>Sehat dimulai dari <span style={{ color: '#108765' }}>Somagede.</span></h1><p>Portal resmi informasi Puskesmas Somagede untuk menghadirkan layanan, agenda, edukasi kesehatan, dan informasi publik secara lebih cepat, rapi, dan mudah diakses dari desktop maupun mobile.</p><div className="actions"><a className="btn primary" href="#layanan">Jelajahi layanan <ArrowRight size={17} /></a><a className="btn secondary" href="#informasi">Lihat informasi</a></div><div className="statGrid"><div className="stat"><strong>9</strong><span>Desa wilayah kerja</span></div><div className="stat"><strong>24/7</strong><span>Info digital tersedia</span></div><div className="stat"><strong>100%</strong><span>Mobile responsive</span></div><div className="stat"><strong>3</strong><span>Role pengelola</span></div></div></div><div className="heroCard"><div className="heroArt"><div className="blob b1" /><div className="blob b2" /><div className="centerSeal"><div className="seal"><Logo /><b>PUSKESMAS<br />SOMAGEDE</b><small style={{ color: '#63726e' }}>Banyumas · Jawa Tengah</small></div></div></div></div></div></section>
            <section className="section" id="layanan"><div className="container"><div className="sectionHead"><div><div className="eyebrow">LAYANAN UTAMA</div><h2>Akses yang terasa sederhana.</h2></div><p>Struktur konten dirancang agar warga langsung menemukan informasi yang mereka butuhkan tanpa harus membuka banyak halaman.</p></div><div className="cards">{[['Pendaftaran & alur layanan', 'Informasi pelayanan, jam buka, serta alur kunjungan pasien.', Stethoscope], ['Agenda kegiatan', 'Jadwal kegiatan lapangan, penyuluhan, skrining, dan program Puskesmas.', CalendarDays], ['Kontak & lokasi', 'Alamat, kanal informasi, serta petunjuk menuju Puskesmas Somagede.', MapPin]].map(([t, p, I]) => { const Icon = I as any; return <div className="card" key={String(t)}><div className="icon"><Icon size={21} /></div><h3>{t as string}</h3><p>{p as string}</p></div> })}</div></div></section>
            <section className="section" id="program"><div className="container"><div className="sectionHead"><div><div className="eyebrow">PROGRAM & EDUKASI</div><h2>Konten kesehatan yang relevan.</h2></div></div><div className="cards">{programs.map(([t, p, d, ico]) => { const Icon = (iconMap as any)[ico]; return <div className="card" key={t}><div className="icon"><Icon size={21} /></div><h3>{t}</h3><p style={{ fontWeight: 700, color: '#243a33', marginBottom: 7 }}>{p}</p><p>{d}</p></div> })}</div></div></section>
            <section className="section" id="informasi"><div className="container"><div className="sectionHead"><div><div className="eyebrow">INFORMASI TERKINI</div><h2>Konten publik seperti di media sosial.</h2></div><p>Contoh tampilan konten yang bisa dipasang staf informasi: poster kegiatan, ucapan hari besar, edukasi, pengumuman, dan agenda pelayanan.</p></div><div className="contentShowcase"><div className="posterCard"><img src="/assets/contoh-konten-hutri-81.png" alt="Contoh konten ucapan HUT ke-81 dari Puskesmas Somagede" /><div className="posterMeta"><span className="badge">CONTOH KONTEN</span><span>17 Agustus 2026</span></div></div><div className="contentCopy"><div className="icon"><Megaphone size={21} /></div><div className="eyebrow">PUBLIKASI PUSKESMAS</div><h3>Ucapan, edukasi, dan pengumuman bisa tampil lebih menarik.</h3><p>Konten seperti poster HUT RI di samping dapat menjadi berita unggulan di beranda. Nantinya staf informasi cukup mengunggah gambar, menulis judul dan keterangan, lalu menerbitkannya dari dashboard.</p><div className="miniList"><div className="mini"><b>Poster & banner</b><span>Format visual untuk ucapan, kampanye kesehatan, dan kegiatan lapangan.</span></div><div className="mini"><b>Agenda kegiatan</b><span>Jadwal tracing TBC, CKG, penyuluhan, posyandu, dan kegiatan desa.</span></div><div className="mini"><b>Informasi layanan</b><span>Pengumuman perubahan jadwal, alur pelayanan, dan informasi penting warga.</span></div></div></div></div></div></section>
        </main>
        <footer className="footer" id="kontak"><div className="container footerGrid"><div><LogoLockup dark /><p style={{ marginTop: 18 }}>Puskesmas Somagede · Jl. Raya Somagede No. 37, Kecamatan Somagede, Kabupaten Banyumas, Jawa Tengah.</p></div><div><b>Layanan</b><p>Informasi publik<br />Agenda kegiatan<br />Edukasi kesehatan</p></div><div><b>Pengelola</b><p>Super Admin<br />Admin<br />Staf Informasi</p></div></div><div className="container" style={{ borderTop: '1px solid #2d5046', marginTop: 25, paddingTop: 15, fontSize: 12, color: '#8faea4' }}>© 2026 Puskesmas Somagede · Portal informasi digital.</div></footer>
    </>
}
