'use client';
import { FormEvent, useState } from 'react';
import Link from 'next/link';
import { LockKeyhole, ShieldCheck, ArrowLeft } from 'lucide-react';
import { LogoLockup } from '@/components/Logo';
export default function Login() {
    const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
    async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(''); const r = await fetch('/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const d = await r.json(); if (!r.ok) { setError(d.error || 'Login gagal'); setLoading(false); return } window.location.href = '/admin' }
    return <main className="loginShell"><div className="loginCard"><LogoLockup /><div style={{ marginTop: 30 }}><div className="eyebrow"><ShieldCheck size={15} /> Area pengelola</div><h1 style={{ fontSize: 32, letterSpacing: '-.04em', margin: '15px 0 5px' }}>Masuk ke dashboard</h1><p style={{ color: '#64736f', lineHeight: 1.6, margin: 0 }}>Akses dibatasi berdasarkan role: super admin, admin, dan staf informasi.</p></div><form className="form" onSubmit={submit}><label className="label">Email</label><input className="field" type="email" autoComplete="username" required value={email} onChange={e => setEmail(e.target.value)} placeholder="nama@puskesmas.id" /><label className="label">Password</label><input className="field" type="password" autoComplete="current-password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="••••••••" />{error && <div className="notice" style={{ background: '#fff0ef', borderColor: '#f0c5c0', color: '#8e342b' }}>{error}</div>}<button className="btn primary" disabled={loading}><LockKeyhole size={17} />{loading ? 'Memeriksa…' : 'Masuk aman'}</button><div className="hint">Sesi memakai cookie HttpOnly + JWT singkat. Kredensial tidak disimpan di browser. Gunakan hash password melalui environment server untuk demo/prototipe ini.</div></form><Link href="/" className="btn secondary" style={{ marginTop: 16, width: '100%' }}><ArrowLeft size={17} /> Kembali ke portal</Link></div></main>
}
