import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { ensureDatabase, db } from '@/lib/db';
import { SEPTEMBER_PERAWAT_SCHEDULES } from '@/lib/perawatSeptember';
import { verifySession } from '@/lib/auth';
export const runtime='nodejs';
async function currentSession(){const c=await cookies();return verifySession(c.get('ps_session')?.value||'');}
const fallbackNurseSchedules=()=>SEPTEMBER_PERAWAT_SCHEDULES.map(([id,title,category,day,time,staff,notes])=>({id,title,category,day,time,staff,notes,published:true}));
export async function GET(req:Request){try{await ensureDatabase();const sql=db();const admin=new URL(req.url).searchParams.get('admin')==='1';if(admin&&!(await currentSession()))return NextResponse.json({error:'Unauthorized'},{status:401});const rows=admin?await sql`SELECT id,title,category,day,time,staff,notes,published,created_at,updated_at FROM site_schedules ORDER BY category,title`:await sql`SELECT id,title,category,day,time,staff,notes,published FROM site_schedules WHERE published=TRUE ORDER BY category,title`;return NextResponse.json({items:rows.length?rows:fallbackNurseSchedules()},{headers:{'Cache-Control':'no-store'}})}catch(error){console.error('SCHEDULE_GET_ERROR',error);return NextResponse.json({items:fallbackNurseSchedules(),source:'fallback'},{headers:{'Cache-Control':'no-store'}})}}
export async function POST(req:Request){try{const s=await currentSession();if(!s||s.role==='staf_informasi')return NextResponse.json({error:'Akses ditolak'},{status:403});await ensureDatabase();const body=await req.json();const title=String(body?.title||'').trim().slice(0,180);const category=String(body?.category||'Layanan').trim().slice(0,100);const day=String(body?.day||'').trim().slice(0,100);const time=String(body?.time||'').trim().slice(0,100);const staff=String(body?.staff||'').trim().slice(0,160);const notes=String(body?.notes||'').trim().slice(0,1000);const published=body?.published!==false;if(!title||!day||!time)return NextResponse.json({error:'Judul, hari/shift, dan jam wajib diisi.'},{status:400});const id=`schedule-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;const sql=db();await sql`INSERT INTO site_schedules (id,title,category,day,time,staff,notes,published) VALUES (${id},${title},${category},${day},${time},${staff},${notes},${published})`;return NextResponse.json({ok:true,id})}catch(error){console.error('SCHEDULE_POST_ERROR',error);return NextResponse.json({error:'Gagal menyimpan jadwal.'},{status:500})}}
export async function DELETE(req:Request){try{const s=await currentSession();if(!s||s.role==='staf_informasi')return NextResponse.json({error:'Akses ditolak'},{status:403});await ensureDatabase();const id=String((await req.json())?.id||'').trim();if(!id)return NextResponse.json({error:'ID jadwal tidak valid.'},{status:400});const sql=db();await sql`DELETE FROM site_schedules WHERE id=${id}`;return NextResponse.json({ok:true})}catch(error){console.error('SCHEDULE_DELETE_ERROR',error);return NextResponse.json({error:'Gagal menghapus jadwal.'},{status:500})}}