import Link from 'next/link'; import { notFound } from 'next/navigation'; import PageTransition from '@/components/PageTransition'; import ServiceSchedule from '@/components/ServiceSchedule'; import { ArrowLeft, ArrowRight, HeartPulse, Stethoscope, CalendarDays, Users } from 'lucide-react';
const data:Record<string,{title:string;desc:string;Icon:any;points:string[]}>= {
 'pendaftaran-dan-pemeriksaan':{title:'Pendaftaran & Pemeriksaan',desc:'Informasi umum mengenai alur kunjungan dan persiapan sebelum mendapatkan pelayanan.',Icon:Stethoscope,points:['Siapkan identitas dan dokumen kepesertaan yang diperlukan.','Ikuti alur pendaftaran sesuai petunjuk petugas.','Untuk kebutuhan khusus, konfirmasi terlebih dahulu melalui kanal Puskesmas.']},
 'cek-kesehatan-gratis':{title:'Cek Kesehatan Gratis',desc:'Ruang informasi untuk program CKG dan kegiatan pemeriksaan kesehatan yang sedang berjalan.',Icon:HeartPulse,points:['Cek informasi jadwal terbaru pada menu Informasi.','Bawa dokumen yang diminta pada pengumuman kegiatan.','Ikuti arahan petugas selama pemeriksaan.']},
 'kesehatan-ibu-dan-anak':{title:'Kesehatan Ibu & Anak',desc:'Informasi KIA, imunisasi, pemantauan tumbuh kembang, dan edukasi keluarga.',Icon:Users,points:['Pantau jadwal pelayanan KIA dan kegiatan posyandu.','Gunakan Asisten untuk mencari informasi umum.','Konsultasikan kondisi kesehatan kepada tenaga kesehatan.']},
 'pencegahan-tbc':{title:'Pencegahan TBC',desc:'Edukasi dan informasi program skrining, tracing, serta tindak lanjut TBC.',Icon:HeartPulse,points:['Kenali gejala dan faktor risiko.','Ikuti skrining sesuai program Puskesmas.','Jangan menghentikan pengobatan tanpa arahan tenaga kesehatan.']},
 'imunisasi':{title:'Imunisasi',desc:'Informasi kegiatan dan edukasi imunisasi di wilayah kerja Puskesmas Somagede.',Icon:HeartPulse,points:['Cek jadwal imunisasi terbaru.','Bawa buku KIA/kartu imunisasi bila tersedia.','Konfirmasi jenis dan jadwal kepada petugas.']},
 'agenda-lapangan':{title:'Agenda Lapangan',desc:'Jadwal kegiatan penyuluhan, skrining, tracing, CKG, dan program Puskesmas.',Icon:CalendarDays,points:['Lihat berita dan agenda terbaru.','Perhatikan lokasi dan waktu kegiatan.','Informasi dapat berubah mengikuti pengumuman resmi.']}
};
export default async function Detail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const item=data[slug];if(!item)notFound();const Icon=item.Icon;return <PageTransition><main><section className="pageHero"><div className="container"><Link href="/layanan" className="sideBack light">← Semua layanan</Link><div className="eyebrow"><Icon size={15}/> LAYANAN</div><h1>{item.title}</h1><p>{item.desc}</p></div></section><section className="section"><div className="container detailGrid"><div className="detailCard"><h2>Informasi utama</h2><div className="detailPoints">{item.points.map(x=><div key={x}><span>✓</span><p>{x}</p></div>)}</div><Link className="btn primary" href="/informasi">Lihat informasi terbaru <ArrowRight size={16}/></Link></div><ServiceSchedule/></div></section></main></PageTransition>}
